services:
  - type: web
    name: movies-recommender-system
    env: python
    buildCommand: "./setup.sh"
    startCommand: "streamlit run main.py"
    repo: https://github.com/Pranav-by/Movie_Recommnder_System
    branch: main
    rootDir: movies-recommender-system
